version: '3.9'

services:
  db:
    image: postgres:latest
    env_file:
      - "database.env"
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  db_data:
